//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elogic.Wamgroup.Sito2023.NetCore.wwwroot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Entities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elogic.Wamgroup.Sito2023.NetCore.wwwroot.Resources.Entities", typeof(Entities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Cerca {
            get {
                return ResourceManager.GetString("Cerca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Codice {
            get {
                return ResourceManager.GetString("Codice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Costo {
            get {
                return ResourceManager.GetString("Costo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Descrizione {
            get {
                return ResourceManager.GetString("Descrizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Dettagli {
            get {
                return ResourceManager.GetString("Dettagli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string DynamicType_Page {
            get {
                return ResourceManager.GetString("DynamicType.Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string DynamicType_Pages {
            get {
                return ResourceManager.GetString("DynamicType.Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns.
        /// </summary>
        public static string Entity_WamgroupRowEntity_NumberOfColumns {
            get {
                return ResourceManager.GetString("Entity.WamgroupRowEntity.NumberOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string Ordine_OrdinaPer {
            get {
                return ResourceManager.GetString("Ordine.OrdinaPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Ordine_Recenti {
            get {
                return ResourceManager.GetString("Ordine.Recenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance.
        /// </summary>
        public static string Ordine_Rilevanza {
            get {
                return ResourceManager.GetString("Ordine.Rilevanza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Ordine_Vecchi {
            get {
                return ResourceManager.GetString("Ordine.Vecchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        public static string Read_more {
            get {
                return ResourceManager.GetString("Read more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ResultsNumberLabelPlural {
            get {
                return ResourceManager.GetString("ResultsNumberLabelPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string ResultsNumberLabelSingular {
            get {
                return ResourceManager.GetString("ResultsNumberLabelSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
